package com.ak.passwordsaver.model.db.entities

import android.arch.persistence.room.ColumnInfo
import android.arch.persistence.room.Entity
import android.arch.persistence.room.Ignore
import android.arch.persistence.room.PrimaryKey

@Entity(tableName = PasswordDBEntity.PASSWORD_TABLE_NAME)
data class PasswordDBEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = COLUMN_PASSWORD_ID)
    var passwordId: Long?,
    @ColumnInfo(name = COLUMN_PASSWORD_NAME)
    var passwordName: String,
    @ColumnInfo(name = COLUMN_PASSWORD_AVATAR_PATH)
    var passwordAvatarPath: String,
    @ColumnInfo(name = COLUMN_PASSWORD_CONTENT)
    var passwordContent: String
) {

    @Ignore
    constructor(passwordId: Long) : this(passwordId, "", "", "")
    @Ignore
    constructor(passwordName: String, passwordContent: String, avatarPath: String?)
            : this(null, passwordName, avatarPath ?: "", passwordContent)

    companion object {
        const val PASSWORD_TABLE_NAME = "Passwords"

        // column names
        const val COLUMN_PASSWORD_ID = "password_id" // autogenerated primary key
        const val COLUMN_PASSWORD_NAME = "password_name" // password alias
        const val COLUMN_PASSWORD_AVATAR_PATH = "password_avatar_path" // url of password picture
        const val COLUMN_PASSWORD_CONTENT = "password_content" // url of password picture
    }
}