package com.ak.core_repo_impl.data.model.db.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey
import com.ak.core_repo_api.intefaces.PasswordRepoEntity

@Entity(tableName = PasswordDBEntity.PASSWORD_TABLE_NAME)
data class PasswordDBEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = COLUMN_PASSWORD_ID)
    var passwordIdValue: Long?,
    @ColumnInfo(name = COLUMN_PASSWORD_NAME)
    var passwordNameValue: String,
    @ColumnInfo(name = COLUMN_PASSWORD_AVATAR_PATH)
    var passwordAvatarPathValue: String,
    @ColumnInfo(name = COLUMN_PASSWORD_CONTENT)
    var passwordContentValue: String
) : PasswordRepoEntity {

    @Ignore
    constructor(passwordId: Long) : this(passwordId, "", "", "")
    @Ignore
    constructor(passwordName: String, passwordContent: String, avatarPath: String?)
            : this(null, passwordName, avatarPath ?: "", passwordContent)

    companion object {
        const val PASSWORD_TABLE_NAME = "Passwords"

        // column names
        const val COLUMN_PASSWORD_ID = "password_id" // autogenerated primary key
        const val COLUMN_PASSWORD_NAME = "password_name" // password alias
        const val COLUMN_PASSWORD_AVATAR_PATH = "password_avatar_path" // url of password picture
        const val COLUMN_PASSWORD_CONTENT = "password_content" // url of password picture
    }

    override fun getPasswordId(): Long? = passwordIdValue

    override fun getPasswordName(): String = passwordNameValue

    override fun getPasswordAvatarPath(): String = passwordAvatarPathValue

    override fun getPasswordContent(): String = passwordContentValue
}